version: "3.8"

services:
  app:
    image: eyupoztrk/finance_tracker:latest
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 12345
      DB_NAME: FinanceTracker
      DB_HOST: db
      LOG_LEVEL: info
      PORT: 3000
      DB_PORT: 5432
      JWT_SECRET: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9eyJpZCI6IjY0NjY5OGUwZTUzYmI4MWVhYzlmYTc4NSIsImV4cCI6MTQ5NDg5NDk2NDMyMDAwfQv0SJjaBuR7SrLmvhVWxAiKgz4T4_rX55wHlD9CfBW10lmYTc4NSIsImV4cCI6MTQ5NDg5NDk2NDMyiLCJhbGciOiJI"
    ports:
      - "3000:3000"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: FinanceTracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
