version: "3.8"

services:
  app:
    image: 
    depends_on:
      - db
    environment:
      DB_USERNAME: 
      DB_PASSWORD: 
      DB_NAME: 
      DB_HOST: 
      LOG_LEVEL: 
      PORT: 
      DB_PORT: 
      JWT_SECRET: ""
    ports:
      - "3000:3000"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
